### ISSUE TITLE
Schönes Projekt, danke für die Übersetzung

### ISSUE THREAD

**Issue by BogusCurry** [wp2opensim/Blender-Projekt-Deutsch-German#1]
Hallo Manni ;D
Hast da ein schönes Projekt am laufen, grosses Danke schön von mir ;D

Have a nice Day ;D

**Comment by wp2opensim** [comment]
Danke Bogus,
ich habe bereits 12000 Zeilen hinzugefügt, etwas über 2000 sind es noch.
Danach kommt die eigentliche Übersetzung, diese muss berücksichtigen was sich im Deutschen eingebürgert hat.
Dazu müssen auch neue Referenzen für neue Wörter erstellt werden.
Voraussichtliche Fertigstellung ist in 4 Monaten.
